SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

CREATE DATABASE IF NOT EXISTS `ucsdb` DEFAULT CHARACTER SET latin1 COLLATE latin1_swedish_ci;
USE `ucsdb`;

CREATE TABLE IF NOT EXISTS `clan` (
  `ClanId` bigint(20) NOT NULL COMMENT 'The ID of the Clan',
  `LastUpdateTime` datetime NOT NULL COMMENT 'The last time when this clan has been loaded',
  `Data` text CHARACTER SET utf8mb4 NOT NULL COMMENT 'The infos and members data of the clan',
  PRIMARY KEY (`ClanId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `player` (
  `PlayerId` bigint(20) NOT NULL,
  `Avatar` text CHARACTER SET utf8mb4 NOT NULL,
  `GameObjects` text CHARACTER SET utf8mb4 NOT NULL,
  PRIMARY KEY (`PlayerId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `stream` (
  `StreamId` bigint(20) NOT NULL,
  `ReplayData` text CHARACTER SET utf8mb4 NOT NULL,
  `BattleData` text CHARACTER SET utf8mb4 NOT NULL,
  PRIMARY KEY (`StreamId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
